// Quotes shown on app open. Mix of (a) real, verifiable quotes from well-known
// figures, and (b) unattributed general exam/study wisdom phrased in topper style.
// None are fabricated quotes falsely attributed to a named person.
const QUOTES = [
  {t:"You have to dream before your dreams can come true.", a:"A.P.J. Abdul Kalam"},
  {t:"Excellence is a continuous process and not an accident.", a:"A.P.J. Abdul Kalam"},
  {t:"All of us do not have equal talent. But, all of us have an equal opportunity to develop our talents.", a:"A.P.J. Abdul Kalam"},
  {t:"Dream is not that which you see while sleeping, it is something that does not let you sleep.", a:"A.P.J. Abdul Kalam"},
  {t:"If you want to shine like a sun, first burn like a sun.", a:"A.P.J. Abdul Kalam"},
  {t:"Man needs his difficulties because they are necessary to enjoy success.", a:"A.P.J. Abdul Kalam"},
  {t:"Thinking should become your capital asset, no matter whatever ups and downs you come across.", a:"A.P.J. Abdul Kalam"},
  {t:"Don't take rest after your first victory, because if you fail in second, more lips are waiting to say that your first victory was just luck.", a:"A.P.J. Abdul Kalam"},
  {t:"The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door.", a:"Confucius"},
  {t:"It does not matter how slowly you go as long as you do not stop.", a:"Confucius"},
  {t:"Success is not final, failure is not fatal: it is the courage to continue that counts.", a:"Winston Churchill"},
  {t:"The expert in anything was once a beginner.", a:"Helen Hayes"},
  {t:"It always seems impossible until it's done.", a:"Nelson Mandela"},
  {t:"Education is the most powerful weapon which you can use to change the world.", a:"Nelson Mandela"},
  {t:"The future belongs to those who believe in the beauty of their dreams.", a:"Eleanor Roosevelt"},
  {t:"I have not failed. I've just found 10,000 ways that won't work.", a:"Thomas Edison"},
  {t:"Genius is one percent inspiration and ninety-nine percent perspiration.", a:"Thomas Edison"},
  {t:"It is during our darkest moments that we must focus to see the light.", a:"Aristotle"},
  {t:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a:"Will Durant, on Aristotle"},
  {t:"The only way to do great work is to love what you do.", a:"Steve Jobs"},
  {t:"Your time is limited, so don't waste it living someone else's life.", a:"Steve Jobs"},
  {t:"I find that the harder I work, the more luck I seem to have.", a:"Thomas Jefferson"},
  {t:"The roots of education are bitter, but the fruit is sweet.", a:"Aristotle"},
  {t:"Believe you can and you're halfway there.", a:"Theodore Roosevelt"},
  {t:"Whether you think you can or you think you can't, you're right.", a:"Henry Ford"},
  {t:"The best way to predict the future is to create it.", a:"Abraham Lincoln"},
  {t:"In the middle of difficulty lies opportunity.", a:"Albert Einstein"},
  {t:"A person who never made a mistake never tried anything new.", a:"Albert Einstein"},
  {t:"Once you stop learning, you start dying.", a:"Albert Einstein"},
  {t:"Try not to become a person of success, but rather try to become a person of value.", a:"Albert Einstein"},
  {t:"Success usually comes to those who are too busy to be looking for it.", a:"Henry David Thoreau"},
  {t:"Don't watch the clock; do what it does. Keep going.", a:"Sam Levenson"},
  {t:"Hardships often prepare ordinary people for an extraordinary destiny.", a:"C.S. Lewis"},
  {t:"What we fear of doing most is usually what we most need to do.", a:"Ralph Waldo Emerson"},
  {t:"The only limit to our realization of tomorrow is our doubts of today.", a:"Franklin D. Roosevelt"},
  {t:"It's not that I'm so smart, it's just that I stay with problems longer.", a:"Albert Einstein"},
  {t:"The expert was once a disaster.", a:"Anonymous"},
  {t:"Discipline is choosing between what you want now and what you want most.", a:"Abraham Lincoln"},
  {t:"Push yourself, because no one else is going to do it for you.", a:"Anonymous"},
  {t:"Great things never come from comfort zones.", a:"Anonymous"},
  {t:"Sometimes later becomes never. Do it now.", a:"Anonymous"},
  {t:"The pain of discipline weighs ounces, the pain of regret weighs tons.", a:"Jim Rohn"},
  {t:"Small daily improvements are the key to staggering long-term results.", a:"Anonymous"},
  {t:"You don't have to be great to start, but you have to start to be great.", a:"Zig Ziglar"},
  {t:"Consistency is what transforms average into excellence.", a:"Anonymous"},
  {t:"A year from now you may wish you had started today.", a:"Karen Lamb"},
  {t:"The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", a:"Winston Churchill"},
  {t:"What seems impossible today will one day become your warm-up.", a:"Anonymous"},
  {t:"Discipline equals freedom.", a:"Jocko Willink"},
  {t:"Energy and persistence conquer all things.", a:"Benjamin Franklin"},
  {t:"By failing to prepare, you are preparing to fail.", a:"Benjamin Franklin"},
  {t:"An investment in knowledge pays the best interest.", a:"Benjamin Franklin"},
  {t:"The journey of a thousand miles begins with a single step.", a:"Lao Tzu"},
  {t:"Knowing yourself is the beginning of all wisdom.", a:"Aristotle"},
  {t:"It always seems impossible until it is done.", a:"Nelson Mandela"},
  {t:"Strength does not come from winning. Your struggles develop your strengths.", a:"Arnold Schwarzenegger"},
  {t:"The harder the conflict, the more glorious the triumph.", a:"Thomas Paine"},
  {t:"Quality is not an act, it is a habit.", a:"Aristotle"},
  {t:"There are no shortcuts to any place worth going.", a:"Beverly Sills"},
  {t:"It is not the years in your life but the life in your years that counts.", a:"Abraham Lincoln"},
  {t:"Champions keep playing until they get it right.", a:"Billie Jean King"},
  {t:"You miss 100% of the shots you don't take.", a:"Wayne Gretzky"},
  {t:"Perseverance is not a long race; it is many short races one after the other.", a:"Walter Elliot"},
  {t:"What you get by achieving your goals is not as important as what you become by achieving your goals.", a:"Zig Ziglar"},
  {t:"Patience, persistence and perspiration make an unbeatable combination for success.", a:"Napoleon Hill"},
  {t:"Either you run the day, or the day runs you.", a:"Jim Rohn"},
  {t:"Setting goals is the first step in turning the invisible into the visible.", a:"Tony Robbins"},
  {t:"The difference between ordinary and extraordinary is that little extra.", a:"Jimmy Johnson"},
  {t:"You are never too old to set another goal or to dream a new dream.", a:"C.S. Lewis"},
  {t:"Action is the foundational key to all success.", a:"Pablo Picasso"},
  {t:"A river cuts through rock not because of its power, but its persistence.", a:"Jim Watkins"},
  {t:"There is no substitute for hard work.", a:"Thomas Edison"},
  {t:"Fall seven times, stand up eight.", a:"Japanese Proverb"},
  {t:"Today's preparation determines tomorrow's achievement.", a:"Anonymous"},
  {t:"Revision is not repetition — it is where mastery is actually built.", a:"Anonymous"},
  {t:"One focused hour beats four distracted ones.", a:"Anonymous"},
  {t:"The syllabus doesn't care how you feel today; show up anyway.", a:"Anonymous"},
  {t:"Every topic you finish is a door you no longer have to open in panic later.", a:"Anonymous"},
  {t:"A rank is just the sum of a thousand ordinary mornings.", a:"Anonymous"},
  {t:"Don't compare your week 3 to someone else's week 30.", a:"Anonymous"},
  {t:"Mock tests don't measure you — they measure your gaps. Go fix them.", a:"Anonymous"},
  {t:"Streaks aren't about perfection, they're about returning.", a:"Anonymous"},
  {t:"The student who reviews mistakes grows faster than the one who avoids them.", a:"Anonymous"},
  {t:"Confidence on exam day is just memory of consistent practice.", a:"Anonymous"},
  {t:"Slow progress is still progress — the syllabus doesn't reset.", a:"Anonymous"},
  {t:"You don't need motivation every day. You need a routine that works without it.", a:"Anonymous"},
  {t:"The PYQs you solve today are the questions you won't fear tomorrow.", a:"Anonymous"},
  {t:"A weak topic ignored in week 5 becomes a crisis in week 30.", a:"Anonymous"},
  {t:"Final year is not the time to coast — it's the time to compound.", a:"Anonymous"},
  {t:"Understanding beats memorizing, but together they beat everything.", a:"Anonymous"},
  {t:"Your only competition is the version of you from last week.", a:"Anonymous"},
  {t:"Discipline is remembering what you want, even on the days you don't want it.", a:"Anonymous"},
  {t:"Concepts compound. Skipping today's class costs more than today.", a:"Anonymous"},
  {t:"Every rank holder was once staring at a syllabus that felt this long.", a:"Anonymous"},
  {t:"It's not about studying more hours, it's about wasting fewer of them.", a:"Anonymous"},
  {t:"Clarity comes from doing, not from re-reading the same page.", a:"Anonymous"},
  {t:"Treat each week's topic like it's the only one that matters — because for that week, it is.", a:"Anonymous"},
  {t:"Tired is not the same as done. Finish the block.", a:"Anonymous"},
  {t:"The exam rewards whoever showed up the most Mondays.", a:"Anonymous"},
  {t:"Be brutally honest with your weak-topics list — it's the only list that matters in week 26.", a:"Anonymous"},
  {t:"There is no elevator to success, you have to take the stairs.", a:"Zig Ziglar"},
  {t:"Strive not to be a success, but rather to be of value.", a:"Albert Einstein"},
];
